name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  CONAN_PRESET: conan-release
  INSTALL_CUDA_WIN: OFF # Temporarily disabled due to a latest MSBuild bug that fails the configure stage
  INSTALL_CUDA_LINUX: ON

jobs:
  build_linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup cmake
      uses: lukka/get-cmake@v3.30.5

    - name: Install CUDA
      if: env.INSTALL_CUDA_LINUX == 'ON'
      uses: Jimver/cuda-toolkit@v0.2.18
      with:
        method: 'network'
        sub-packages: '["nvcc", "cudart"]'
        cuda: '12.6.2'

    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Setup Conan profile
      run: conan profile detect

    - name: Install dependencies
      run: conan install . -s build_type=${{env.BUILD_TYPE}} -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True --build=missing

    - name: Configure
      run: cmake --preset ${{env.CONAN_PRESET}} -DBUILD_TESTS=ON -DBUILD_CUDA=${{env.INSTALL_CUDA_LINUX}}

    - name: Build
      run: cmake --build --preset ${{env.CONAN_PRESET}} --target lut_loader_test -j

    - name: Run unit tests
      working-directory: ${{github.workspace}}/src/test
      run: ${{github.workspace}}/build/${{env.BUILD_TYPE}}/src/test/lut_loader_test

  build_windows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Setup cmake
      uses: lukka/get-cmake@v3.30.5

    - name: Install CUDA
      if: env.INSTALL_CUDA_WIN == 'ON'
      uses: Jimver/cuda-toolkit@v0.2.18
      with:
        method: 'network'
        sub-packages: '["nvcc", "cudart", "visual_studio_integration"]'
        cuda: '12.6.2'

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Setup Conan profile
      run: conan profile detect

    - name: Install dependencies
      run: conan install . -s build_type=${{env.BUILD_TYPE}} --build=missing

    - name: Configure
      run: cmake --preset conan-default -DBUILD_TESTS=ON -DBUILD_CUDA=${{env.INSTALL_CUDA_WIN}}

    - name: Build
      run: cmake --build --preset ${{env.CONAN_PRESET}} --target lut_loader_test -j

    - name: Run unit tests
      working-directory: ${{github.workspace}}/src/test
      run: ${{github.workspace}}\\build\\src\\test\\${{env.BUILD_TYPE}}\\lut_loader_test

  build_macos:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Setup cmake
      uses: lukka/get-cmake@v3.30.5

    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Setup Conan profile
      run: conan profile detect

    - name: Install dependencies
      run: conan install . -s build_type=${{env.BUILD_TYPE}} --build=missing

    - name: Configure
      run: cmake --preset ${{env.CONAN_PRESET}} -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build --preset ${{env.CONAN_PRESET}} --target lut_loader_test -j

    - name: Run unit tests
      working-directory: ${{github.workspace}}/src/test
      run: ${{github.workspace}}/build/${{env.BUILD_TYPE}}/src/test/lut_loader_test
